### ISSUE TITLE
DAS_Tool "Execution halted" before final output is created

### ISSUE THREAD

**Issue by reslp** [cmks/DAS_Tool#20] opened 2018-06-15 09:08 UTC
Dear Christian,

I am having troubles with DAS_Tool V.1.1.0. It seems to create some output files but not the final output. I have created bins with three different binning tools: concoct, MaxBin and Metabat. 

My bin files which I use as input for DAS_Tool look like this:
```
$head pleu_concoct_for_DAS_tool.tsv
NODE_2_length_50931_cov_33.5402	concoct.1
NODE_3_length_48627_cov_75.1793	concoct.22
NODE_4_length_48329_cov_10.0293	concoct.5
NODE_5_length_46674_cov_9.58524	concoct.5
NODE_6_length_42150_cov_9.50275	concoct.5
NODE_7_length_40764_cov_11.1834	concoct.5
NODE_8_length_40104_cov_8.31451	concoct.24
NODE_9_length_39949_cov_9.41567	concoct.5
NODE_10_length_39145_cov_9.62804	concoct.5
NODE_11_length_38623_cov_9.83874	concoct.5

$ head pleu_maxbin_for_DAS_tool.tsv
NODE_1_length_52827_cov_10.1315	maxbin.1
NODE_3_length_48627_cov_75.1793	maxbin.1
NODE_4_length_48329_cov_10.0293	maxbin.1
NODE_5_length_46674_cov_9.58524	maxbin.1
NODE_6_length_42150_cov_9.50275	maxbin.1
NODE_7_length_40764_cov_11.1834	maxbin.1
NODE_9_length_39949_cov_9.41567	maxbin.1
NODE_10_length_39145_cov_9.62804	maxbin.1
NODE_11_length_38623_cov_9.83874	maxbin.1
NODE_12_length_35549_cov_9.91449	maxbin.1

$head pleu_metabat_for_DAS_tool.tsv
NODE_5409_length_5181_cov_1.42066	metabat.1
NODE_5457_length_5137_cov_1.56786	metabat.1
NODE_5482_length_5119_cov_0.954728	metabat.1
NODE_6073_length_4670_cov_2.40634	metabat.1
NODE_6212_length_4555_cov_1.10388	metabat.1
NODE_6228_length_4543_cov_1.71626	metabat.1
NODE_6481_length_4361_cov_0.961502	metabat.1
NODE_6887_length_4097_cov_0.739547	metabat.1
NODE_6949_length_4065_cov_1.74784	metabat.1
NODE_6991_length_4043_cov_1.26047	metabat.1
```

I run DAS_Tool like this:
`
~/downloads/DAS_Tool-1.1.0/DAS_Tool -i pleu_concoct_for_DAS_tool.tsv,pleu_maxbin_for_DAS_tool.tsv,pleu_metabat_for_DAS_tool.tsv -l concoct,maxbin,metabat -c Pleu_metagenome_assembly.fasta -o DAS_Tool_out --threads 24 --search_engine blast
`

The output from DAS_Tool looks like this:

```
predicting genes using prodigal
identifying single copy genes using blast
running DAS Tool with 24 threads
evaluating bin-sets
starting bin selection from  21  bins

Execution halted
```

DAS_Tool also creates several output files, however several files seem to be missing. For example the summary file:

```
-rw-rw-r-- 1 philipp philipp     2329 Jun 14 17:33 DAS_Tool_out_concoct.eval
-rw-rw-r-- 1 philipp philipp      668 Jun 14 17:33 DAS_Tool_out_maxbin.eval
-rw-rw-r-- 1 philipp philipp      483 Jun 14 17:33 DAS_Tool_out_metabat.eval
-rw-rw-r-- 1 philipp philipp 49843166 Jun 14 17:30 DAS_Tool_out_proteins.faa
-rw-rw-r-- 1 philipp philipp    18450 Jun 14 17:33 DAS_Tool_out_proteins.faa.archaea.scg
-rw-rw-r-- 1 philipp philipp    51284 Jun 14 17:30 DAS_Tool_out_proteins.faa.bacteria.scg
-rw-rw-r-- 1 philipp philipp  4032468 Jun 14 17:33 DAS_Tool_out.seqlength
```

Am I missing something? 
I would greatly appreciate your help in solving this.

Many thanks,

Philipp

**Comment by reslp** [comment] 2018-06-15 10:17
I also just ran the same analysis with the --debug flag which gives me this:
```starting bin selection from  21  bins

Error in file(file, "rt") : cannot open the connection
Calls: cherry_pick -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'DAS_Tool_out_DASTool_summary.txt': No such file or directory
Execution halted``

**Comment by cmks** [comment] 2018-06-19 21:43
Hi Philipp,

It seems like you found a bug which causes DAS Tool to crash if all bins in the input set are below the pre-defined score threshold. Can you please check if any of the scores in your bin evaluation files (DAS_Tool_out_concoct.eval, DAS_Tool_out_maxbin.eval, DAS_Tool_out_metabat.eval) are greater than 0.5? 
Alternatively, you can also make DAS Tool report bins of lower quality in setting the score threshold
to a lower value (e.g. `--score_threshold -1`).

Let me know if this solves your problem. Also thanks for reporting this bug.
Christian

**Comment by reslp** [comment] 2018-06-20 11:58
Hi Christian,

I checked the *.eval files and it seems that none of my bin have a score > 0.5 (values of third to last column). I also tried to run DAS_Tool now with a different score threshold but also this did not work. Here are my commands:

I tried

`~/downloads/DAS_Tool-1.1.0/DAS_Tool -i pleu_concoct_for_DAS_tool.tsv,pleu_maxbin_for_DAS_tool.tsv,pleu_metabat_for_DAS_tool.tsv -l concoct,maxbin,metabat -c Pleu_metagenome_assembly.fasta -o DAS_Tool_out --threads 24 --search_engine blast --debug --score_threshold 0`
and
` ~/downloads/DAS_Tool-1.1.0/DAS_Tool -i pleu_concoct_for_DAS_tool.tsv,pleu_maxbin_for_DAS_tool.tsv,pleu_metabat_for_DAS_tool.tsv -l concoct,maxbin,metabat -c Pleu_metagenome_assembly.fasta -o DAS_Tool_out --threads 24 --search_engine blast --debug --score_threshold -1
`

Both times DAS_Tool created the summary file `DAS_Tool_out_DASTool_summary.txt`. However there was still an error:

```
Error: Faceting variables must have at least one value
Execution halted
```

Does this mean the run is complete or is there still something missing?

Thank you for your help!

Philipp

**Comment by cmks** [comment] 2018-06-20 23:46
Hi Philipp,

Your run is complete and you should have a scaffolds2bin file and a summary file in your output directory. However, in the end DAS Tool is triggering a script to plot an overview of the number of reconstructed high quality bins. Because no high quality bins were found, the script fails and produces an error message. 
It's another bug which is connected to the first one. I'll have to fix this in the next release.

Thanks for reporting these bugs!
Cheers,
Christian

**Comment by reslp** [comment] 2018-06-21 07:32
Hi Christian,

OK thank you for the explanation and for your help. I guess now I have to figure out why I only get low-quality bins.

best,

Philipp

**Comment by neslihan-tas** [comment] 2018-06-26 00:37
Hi Christian,

I am running into the same problem but with sample data.

`DAS_Tool -i sample.human.gut_concoct_scaffolds2bin.tsv,sample.human.gut_maxbin2_scaffolds2bin.tsv,sample.human.gut_metabat_scaffolds2bin.tsv,sample.human.gut_tetraESOM_scaffolds2bin.tsv -l concoct,maxbin,metabat,tetraESOM -c sample.human.gut_contigs.fa -o sample_output/DASToolRun-test -t 4 --db_directory /global/home/myhome/software/DAS_Tool-master/db --debug`

predicting genes using prodigal
identifying single copy genes using usearch
running DAS Tool with 4 threads
evaluating bin-sets
starting bin selection from  0  bins

Error in file(file, "rt") : cannot open the connection
Calls: cherry_pick -> read.table -> file
In addition: Warning messages:
1: In max(bin_summary$score) :
  no non-missing arguments to max; returning -Inf
2: In file(file, "rt") :
  cannot open file 'sample_output/DASToolRun-test_DASTool_summary.txt': No such file or directory
Execution halted

I tried the search with usearch (v9.1.13) and blast as search engines but error remains the same.

Any suggestions?

Many thanks

N

**Comment by cmks** [comment] 2018-07-16 04:22
I'm closing this. The described problem was caused by an old, unsupported version of prodigal (< 2.6).

**Closed by cmks** 2018-07-16 04:22 UTC
